### PR TITLE
json conversion of general.txt

### PR DESCRIPTION
**Pull request by JayTurnr**
General.txt should really be general.csv (or rather tsv, for tab-seperated-value)

### CODE REVIEW

**Comment by reptilezsweden** [comment]
Makes no difference. File extension doesn't affect the content ;)

**Comment by reptilezsweden** [comment]
Just changing the file extension doesn't change the content. (I can just as easily open a .txt in excel as I can in notepad) 
What I'm guessing that you want is to change the format of the content to make it more readable.

**Comment by dantheother** [comment]
I think @JayTurnr is referring to how GitHub displays csv/tsv files - https://help.github.com/articles/rendering-csv-and-tsv-data/

**Comment by JayTurnr** [comment]
Yep, that's correct! Because have you seen the size of this repo?

Anyway, my pull request is about adding a JSON file which is much easier to use in software packages.

**Pull request closed without merging**
