### PR TITLE
i18n: Rename merged.txt files

### PR DESCRIPTION
**Pull request by JayTurnr**
merged.txt files now show language name

### CODE REVIEW

**Comment by ryankane** [comment]
I agree with the renaming of the files.

**Comment by ryankane** [comment]
You should rebase your branch with master and rename the files and force-push so there are no merge conflicts @JayTurnr

**Comment by JayTurnr** [comment]
@ryankane @ZeChrales Fully rebased

**Comment by Selim042** [comment]
Kinda related, what file type are these files?  I'm looking to use the translations in a Discord bot of mine and hoping someone already has a tool to parse these in Java.

**Comment by ryankane** [comment]
@Selim042 The files are a serialized text dump of a [Protobuf](https://en.wikipedia.org/wiki/Protocol_Buffers) data stream.

I wrote a JavaScript parser here:

> https://github.com/ZeChrales/PogoAssets/issues/14#issuecomment-439411933

**Pull request closed without merging**
